# Generated by Django 3.1.6 on 2022-11-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20221114_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_gain',
            field=models.FloatField(default=0),
        ),
    ]
