# Generated by Django 3.1.6 on 2022-11-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20221114_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_gain',
            field=models.IntegerField(default=0),
        ),
    ]
