# Generated by Django 3.1.6 on 2022-11-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20221115_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='Unknown', max_length=20, unique=True),
        ),
    ]
