# Generated by Django 4.0.8 on 2022-11-02 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_photo_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='user',
            new_name='author',
        ),
    ]
