# Generated by Django 3.1.6 on 2022-11-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20221106_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='event',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='size',
            field=models.FloatField(default=0),
        ),
    ]
