# Generated by Django 3.1.6 on 2022-11-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20221106_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='pot_ratio',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='plant',
            name='pot_size',
            field=models.FloatField(default=20),
        ),
    ]
