# Generated by Django 3.1.6 on 2022-11-07 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_auto_20221106_2310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['-start_date']},
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='plant_id',
            new_name='plant',
        ),
    ]
