# Generated by Django 3.1.6 on 2022-11-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_auto_20221109_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='plant',
            name='pot_ratio',
            field=models.FloatField(default=0.4),
        ),
    ]
