# Generated by Django 3.1.6 on 2022-11-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_auto_20221111_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='event',
            field=models.IntegerField(null=True),
        ),
    ]
