# Generated by Django 3.1.6 on 2022-11-13 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_auto_20221111_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('species', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
