# Generated by Django 3.1.6 on 2022-11-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0019_auto_20221116_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='pot_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
