# Generated by Django 3.1.6 on 2022-11-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0020_plant_pot_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='beforeimage',
            field=models.ImageField(null=True, upload_to='post/'),
        ),
    ]
