# Generated by Django 3.1.6 on 2022-11-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0021_photo_beforeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='pot_image',
            field=models.ImageField(null=True, upload_to='post/'),
        ),
    ]
