# Generated by Django 3.1.6 on 2022-12-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0022_auto_20221130_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='harvest_weight',
            field=models.FloatField(default=0),
        ),
    ]
